In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv("HomePricing.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

price=(m1*area)+(m2*bedrooms)+(m3*age)+c

In [4]:
df.bedrooms.median() #Median of bedrooms

3.5

In [5]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [9]:
df.bedrooms.fillna(median_bedrooms) #Substituting the value of bedrooms with the median's floor value where number of bedrooms is missing

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [10]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [11]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [12]:
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [13]:
reg.intercept_

383724.9999999998

In [14]:
reg.predict([[3000,3,40]])

array([444400.])

In [16]:
(137.25*3000)+(-26025*3)+(-6825*40)+(383724.9999999998)

444399.9999999998

In [17]:
reg.predict([[2600,3,20]])

array([526000.])