In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df=pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [9]:
model.predict([[5000]])

array([859554.79452055])

In [10]:
import pickle

In [11]:
with open('model_pickle','wb') as f: #Opening file in wb mode
    pickle.dump(model,f) #Dump model in this file

In [13]:
with open('model_pickle','rb') as f: #Opening the file in rb mode   
    mp=pickle.load(f) #Loading the model

In [15]:
mp.predict([[5000]]) #Predicting the price of the home whose area is 5000 sq ft

array([859554.79452055])

In [17]:
import joblib

In [18]:
joblib.dump(model,'model_joblib')

['model_joblib']

In [19]:
mj=joblib.load('model_joblib')

In [20]:
mj.predict([[5000]])

array([859554.79452055])

In [21]:
mj.coef_

array([135.78767123])

In [22]:
mj.intercept_

180616.43835616432